spring:
  application:
    name: shoppingmall

---
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/shoppingmall
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret:
    key: ${JWT-SECRET-KEY}
