### 상품 좋아요 토글
POST http://localhost:8080/api/products/3/like
Authorization: {{Authorization}}
Content-Type: application/json

{
  "contentType": "PRODUCT",
  "contentId": 3
}


### 댓글 좋아요 토글
POST http://localhost:8080/api/comments/2/like
Authorization: {{Authorization}}
Content-Type: application/json

{
  "contentType": "COMMENT",
  "contentId": 2
}

### 내가 좋아요한 상품 조회 (페이징)
GET http://localhost:8080/api/products/like?pageNum=1&isDesc=true
Authorization: {{Authorization}}
Content-Type: application/json

### 내가 좋아요한 댓글 조회 (페이징)
GET http://localhost:8080/api/comments/like?pageNum=1&isDesc=true
Authorization: {{Authorization}}
Content-Type: application/json